# railway.toml - Optimized build with Smart Docling

[build]
builder = "nixpacks"
# Staged installation for better Docker layer caching
buildCommand = """
  pip install --upgrade pip wheel && \
  pip install --no-cache-dir fastapi uvicorn python-multipart python-dotenv && \
  pip install --no-cache-dir aiofiles asyncpg sqlalchemy && \
  pip install --no-cache-dir openai pydantic pydantic-settings && \
  pip install --no-cache-dir -r requirements.txt
"""

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Build optimization environment
[build.env]
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_DEFAULT_TIMEOUT = "100"
NIXPACKS_PYTHON_VERSION = "3.11"

# Smart Docling build settings
DOCLING_CACHE_DIR = "/tmp/docling_cache"

# Runtime environment for smart processing
[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

# Smart Docling configuration
ENVIRONMENT = "development"
DOCLING_LAZY_LOAD = "true"
SKIP_DOCLING_HEAVY_MODELS = "true"