# railway.toml - simple version for Railway

[build]
builder = "nixpacks"
# Remove custom buildCommand - let Railway auto-detect requirements.txt

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Build optimization environment
[build.env]
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_DEFAULT_TIMEOUT = "100"
NIXPACKS_PYTHON_VERSION = "3.11"

# Runtime environment for smart processing
[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

# Smart Docling configuration
ENVIRONMENT = "development"
DOCLING_LAZY_LOAD = "true"
SKIP_DOCLING_HEAVY_MODELS = "true"